#!/bin/sh


if [ -z "$1" ]; then
    echo "Usage: $0 up|down|mute"
fi

eww open volume

if [ "$1" = "up" ]; then
    pamixer -i 2
elif [ "$1" = "down" ]; then
    pamixer -d 2
elif [ "$1" = "mute" ]; then
    pamixer -t
fi

eww close volume