#!/usr/bin/env bash

# pkill mpv
proc=$(ps aux | grep -i "youplay" | choose 1)
kill $proc &


clipp=$(xsel --clipboard)
mpv --no-sub-auto --hwdec=vaapi --x11-name="youplay" --title="youplay" --keepaspect --speed=1.0 --ytdl-format='bestvideo[height<=?1080]+bestaudio/best' --input-ipc-server="/home/bresilla/.config/mpv/control" --load-unsafe-playlists --no-terminal "${1:-$clipp}"
#--panscan=1.0 --no-keepaspect
