#!/bin/sh

clipp=$(xsel --clipboard)
yt-dlp -i --yes-playlist --restrict-filenames -o "%(autonumber)s-%(title)s.%(ext)s" --cookies-from-browser chrome:~/.var/app/org.chromium.Chromium --no-part --skip-unavailable-fragments --no-overwrites ${1:-$clipp}
