return {
  api = 1, id = "tsugumori", name = "Tsugumori",
  views = {
    keyboard = "themes.layouts.views.keyboard",
    lule_page = "themes.layouts.views.lule_page",
    bar = "themes.layouts.views.bar",
    side_panel = "themes.layouts.views.side_panel",
    tasks_page = "themes.layouts.views.tasks_page",
    calendar_page = "themes.layouts.views.calendar_page",
    planner_widgets = "themes.layouts.views.planner_widgets",
    net_pages = "themes.layouts.views.net_pages",
    power_page = "themes.layouts.views.power_page",
    bar_page = "themes.layouts.views.bar_page",
    connectivity = "themes.layouts.views.connectivity",
    sound_page = "themes.layouts.views.sound_page",
    equalizer_page = "themes.layouts.views.equalizer_page",
    utilities = "themes.layouts.views.utilities",
    bottom = "themes.layouts.views.bottom",
    assistant = "themes.layouts.views.assistant",
    drop = "themes.layouts.views.drop",
    dashboard_performance = "themes.layouts.views.dashboard_performance",
    graphs = "themes.layouts.views.graphs",
    dashboard_battery = "themes.layouts.views.dashboard_battery",
    dashboard_weather = "themes.layouts.views.dashboard_weather",
    dashboard = "themes.layouts.views.dashboard",
    notification_history = "themes.layouts.views.notification_history",
    rail = "themes.tsugumori.views.rail",
    frame = "themes.tsugumori.views.frame",
    levels = "themes.layouts.views.levels",
    notifications = "themes.layouts.views.notifications",
    polkit = "themes.layouts.views.polkit",
    authsteps = "themes.layouts.views.authsteps",
    headphones = "themes.layouts.views.headphones",
    session = "themes.layouts.views.session",
    launcher = "themes.layouts.views.launcher",
    capture_view = "themes.layouts.views.capture_view",
    capture_editor = "themes.layouts.views.capture_editor",
    dashboard_media = "themes.layouts.views.dashboard_media",
  },
  tokens = require("themes.tsugumori.tokens"),
  motion = "themes.tsugumori.motion",
  components = "themes.tsugumori.components",
  lock = "themes.tsugumori.lock", greet = "themes.tsugumori.greet",
}
