#!/bin/bash
source /home/bresilla/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -theme-str "*{accent: ${color1:-#FFFFFF}; bckgrd: ${color0:-#000000};}")
BROWSER=org.mozilla.firefox

srch=search
mark=bookmarks
loca=proxmox
hist=history
list=playlist
pkgs=packages
apps=app-list

another=$(echo "\
$hist
$mark
$loca
$srch
$list
$apps
$pkgs\
" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "search: ")


if [ "$another" == "$srch" ] ; then
    surfraw -browser=$BROWSER $(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' | rofi "${ROFI_OPTIONS[@]}" -kb-row-select 'Tab' -kb-row-tab 'Control+space' -dmenu -i -p 'bangs: ')

elif [ "$another" == "$hist" ] ; then
    exec /home/bresilla/.config/rofi/menu/fox

elif [ "$another" == "$mark" ] ; then
    LINK=$(/env/bin/bookmark --file "/home/bresilla/.local/share/bookmark/webmarks_v0.1.json" list -g default| tail -n+3 | sed 's/^\w*\s*//' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'bookmarks: ' | /env/bin/choose 1)
    [[ -z $LINK ]] && exit 1
    $BROWSER $LINK

elif [ "$another" == "$loca" ] ; then
    LINK=$(/env/bin/bookmark --file "/home/bresilla/.local/share/bookmark/webmarks_v0.1.json" list -g proxmox | tail -n+3 | sed 's/^\w*\s*//' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'bookmarks: ' | /env/bin/choose 1)
    [[ -z $LINK ]] && exit 1
    $BROWSER $LINK

elif [ "$another" == "$list" ] ; then
    LINK=$(/env/bin/bookmark --file "/home/bresilla/.local/share/bookmark/playmarks_v0.1.json" list | tail -n+3 | sed 's/^\w*\s*//' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'bookmarks: ' | /env/bin/choose 1)
    [[ -z $LINK ]] && exit 1
    /env/dot/.func/media/play $LINK


elif [ "$another" == "$apps" ] ; then
    LINK=$(/env/bin/bookmark --file "/home/bresilla/.local/share/bookmark/climarks_v0.1.json" list | tail -n+3 | sed 's/^\w*\s*//' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'bookmarks: ' | /env/bin/choose 1)
    [[ -z $LINK ]] && exit 1
    $BROWSER $LINK

elif [ "$another" == "$pkgs" ] ; then
    LINK=$(rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "package: ")
    $BROWSER "https://pkgs.org/search/?q=$LINK"

elif [ -z "$another" ] ; then
    #https://github.com/BelkaDev/RofiFtw
    handler=$(dirname $0)/duckduck
    rofi "${ROFI_OPTIONS[@]}" -modi blocks -show blocks -blocks-wrap $handler -display-blocks "SEARCH" 2>/dev/null
    [ -f "/tmp/ddgrofi.tmp" ] && $BROWSER "https://duckduckgo.com/?q=$(cat "/tmp/ddgrofi.tmp")" || exit 0

else
    $BROWSER "https://duckduckgo.com/?q=$another"
    #exec nohup $another > /dev/null 2>&1 &
fi
