#!/bin/bash
source /home/bresilla/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -theme-str "*{accent: ${color1:-#FFFFFF}; bckgrd: ${color0:-#000000};}")
edit_with="kitty --class=til"

another=$(echo "CONFIGS
SCRIPTS
ROFMENU
PROFILE" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "CONFIGS: ")

browse(){
    if [[ "$2" == "$1" ]]; then
        selected=$(ls -A --group-directories-first "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "$1: ")
    else
        selected=$({ ls -A --group-directories-first "$1/" & echo ".."; } | cat | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "$1: ")
    fi

    [[ -z $selected ]] && exit
    if [[ "$selected" == ".." ]]; then
        browse "$(dirname $1)" $2
    elif [[ -f $1/$selected ]]; then
        $edit_with -e nvim $1/$selected
    elif [[ -d $1/$selected ]]; then
        browse $1/$selected $2
    else
        touch $1/$selected
        chmod +x $1/$selected
        $edit_with -e nvim $1/$selected
    fi
}

if [ "$another" == "PROFILE" ] ; then
    selected=$(echo "/env/dot/.zshrc
/env/dot/.bashrc
/env/dot/.profile
/env/dot/.startup
/env/dot/.aliases
/env/dot/.other/variables
/env/dot/.config/promptline
/env/dot/.config/git/config
/env/dot/.config/tmux/tmux.conf
/env/dot/.config/nixpkgs/home.nix" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "shell: ")
[[ -z $selected ]] && exit
    $edit_with -e nvim $selected

elif [ "$another" == "CONFIGS" ] ; then
    browse /env/dot/.config /env/dot/.config;

elif [ "$another" == "SCRIPTS" ] ; then
    browse /env/dot/.func /env/dot/.func;

elif [ "$another" == "ROFMENU" ] ; then
    browse /env/dot/.config/rofi/menu /env/dot/.config/rofi/menu;

else
    echo $another
fi
