#!/bin/bash
source /home/bresilla/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -theme-str "*{accent: ${color1:-#FFFFFF}; bckgrd: ${color0:-#000000};}")

 name=$(CLIntacts  --database=/home/bresilla/Sets/contacts list -i $(CLIntacts --database=/home/bresilla/Sets/contacts list | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "contacts: " | cut -d. -f1))

if [ -z "$name" ] ; then
    echo "nothing selected"
else
    printf "$name" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "contacts: " | cut -d. -f2 | xargs | xclip -sel clip
fi
