#!/bin/bash
PADDINGS="40% 0 0 42%"
source /home/bresilla/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_icon -theme-str "*{accent: ${color1:-#FFFFFF}; spacing: $PADDINGS;}")


PADDINGS="40% 0 0 46%"
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_icon -theme-str "*{accent: ${FOREGROUND:-#000000}; spacing: $PADDINGS;}")

disp=$(echo -e "1\n2" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "Select layout:")
if [ "$disp" == "1" ] ; then
    exec xrandr --output eDP-1 --primary --mode 3840x2160 --pos 0x0 --output DP-1 --off
elif [ "$disp" == "2" ] ; then
    exec xrandr --output eDP-1 --primary --mode 3840x2160 --pos 0x2160 --output DP-1 --mode 3840x2160 --pos 0x0
fi
