#!/usr/bin/env bash
source /home/bresilla/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -theme-str "*{accent: ${color1:-#FFFFFF}; bckgrd: ${color0:-#000000};}")

TASK=$(task | tail -n+4 | head -n-2 | awk '{print $0}' | column -t -s $'\t' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p 'task: ' | awk '{print $1}') 

[[ -z $TASK ]] && exit 1
task done $TASK
