#!/bin/bash

# cat $TMP/lule_colors > $HOME/.cache/wal/colors
cp $TEMP/lule_colors $HOME/.cache/wal/colors
cp $TEMP/lule_theme $HOME/.cache/wal/theme
cp $TEMP/lule_wallpaper $HOME/.cache/wal/wallpaper


create_files(){
    ### === PRINTING THINGS TO FILES === ###
    wallpaper="none"
    theme="none"
    fore=$(sed -n '16p' $HOME/.cache/wal/colors)
    back=$(sed -n '1p' $HOME/.cache/wal/colors)
    col1=$(sed -n '2p' $HOME/.cache/wal/colors)
    # COLORS.SH (used by shells - bash,zsh,fish...)
    printf "foreground=\"$fore\"\nbackground=\"$back\"\ncursor=\"$col1\"\n" > $HOME/.cache/wal/colors.sh
    awk '{print "color" NR-1 "=\"" $0 "\""}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.sh

    # COLORS.JSON (used by FREFOX)
    printf "{\n\t\"wallpaper\": \"$wallpaper\",\n\t\"theme\": \"$theme\",\n" > $HOME/.cache/wal/colors.json
    printf "\t\"special\": {\n\t\t\"background\": \"$back\",\n\t\t\"foreground\": \"$fore\",\n\t\t\"cursor\": \"$col1\"\n\t},\n\t\"colors\": {\n" >> $HOME/.cache/wal/colors.json
    awk '{print "\t\t\"color" NR-1 "\": \"" $0 "\","}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.json
    truncate -s-2 $HOME/.cache/wal/colors.json; printf "\n\t}\n}" >> $HOME/.cache/wal/colors.json

    # COLORS.YAML (used by ALACRITY)
    # cat ~/.cache/wal/colors.json | jq | yq -y > $HOME/.cache/wal/colors.yml
    printf "special:\n  background: \"$back\"\n  foreground: \"$fore\"\n  cursor: \"$col1\"\n\ncolors:\n" > $HOME/.cache/wal/colors.yml
    awk '{print "  color" NR-1 ": \"" $0 "\""}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.yml

    # COLORS.TOML (used by ALACRITY)
    printf "[special]\nbackground = \"$back\"\nforeground = \"$fore\"\ncursor = \"$col1\"\n\n[colors]\n" > $HOME/.cache/wal/colors.toml
    awk '{print "color" NR-1 " = \"" $0 "\""}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.toml

    # COLORS.INI (used by POLYBAR)
    printf "[colors]\n\tforeground=$fore\n\tbackground=$back\n\tcursor=$col1\n" > $HOME/.cache/wal/colors.ini
    awk '{print "\tcolor" NR-1 "=" $0 }' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.ini
 
    # COLORS.SCSS (used for STYLING)
    printf "\$foreground: $fore;\n\$background: $back;\n\n" > $HOME/.cache/wal/colors.scss
    awk '{print "$color" NR-1 ": " $0 ";"}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.scss

    # COLORS.CSS (used for styling web pages)
    printf "@define-color foreground $fore;\n@define-color background $back;\n" > $HOME/.cache/wal/colors.css
    awk '{print "@define-color color" NR-1 " " $0 ";"}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.css
    printf ":root {\n\t--foreground: $fore;\n\t--background: $back;\n" > $HOME/.cache/wal/colors_def.css
    awk '{print "\t--color" NR-1 ": " $0 ";"}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors_def.css
    printf "}\n" >> $HOME/.cache/wal/colors_def.css
 
    # COLORS.RASI (used for STYLING)
    printf "* {\n\tforeground: $fore;\n\tbackground: $back;\n" > $HOME/.cache/wal/colors.rasi
    awk '{print "\tcolor" NR-1 ": " $0 ";"}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.rasi
    printf "}" >> $HOME/.cache/wal/colors.rasi

    # COLORS.CONF (used by KITTY)
    printf "foreground\t$fore\nbackground\t$back\ncursor\t$col1\n\n" > $HOME/.cache/wal/colors.conf
    awk '{print "color" NR-1 "\t " $0}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.conf

    # COLORS_W.CONF (used by HYPR)
    printf "\$foreground=rgb(${fore//#})\n\$background=rgb(${back//#})\n\n" > $HOME/.cache/wal/colors_hypr_2.conf
    awk '{print "$color" NR-1 "=rgb("substr($0, 2)")"}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors_hypr_2.conf
    cp $HOME/.cache/wal/colors_hypr_2.conf $HOME/.cache/wal/colors_hypr.conf
    
    # COLORS.VIM
    printf "let foreground= \"$fore\"\nlet background= \"$back\"\n" > $HOME/.cache/wal/colors.vim
    awk '{print "let color" NR-1 "= \"" $0 "\""}' $HOME/.cache/wal/colors >> $HOME/.cache/wal/colors.vim

    # SEQUENCES (escape codes sent to all '/dev/pts/*')
    printf "]10;$fore\\]11;$back\\]12;$col1\\]13;$back\\]17;$col1\\]19;$back\\" > $HOME/.cache/wal/sequences
    awk '{print "]4;" NR-1 ";" $0"\\"}' ORS='' $HOME/.cache/wal/colors >> $HOME/.cache/wal/sequences

    #update logo colors
    sed -i "s/fill=\"#\([^\"]*\)\"/fill=\"$col1\"/" /home/bresilla/.config/bresilla.svg
}

create_files

#sent color sequences to all ppts (most important piece of this script)
colors_to_tty(){
    for tt in /dev/pts/*; do
        re='^[0-9]+$'; [[ $(basename $tt) =~ $re ]] && cat $HOME/.cache/wal/sequences > $tt;
    done
}
colors_to_tty &


# scp -r /home/bresilla/.cache/lule/colors borg.zerotier:~/.cache/lule/colors &> /dev/null & disown
# scp -r /home/bresilla/.cache/lule/colors robo.zerotier:~/.cache/lule/colors &> /dev/null & disown
# scp -r /home/bresilla/.cache/lule/colors echo.zerotier:~/.cache/lule/colors &> /dev/null & disown

source $HOME/.cache/wal/colors.sh

hyprctl hyprpaper preload $(cat /home/bresilla/.cache/wal/wallpaper)
hyprctl hyprpaper wallpaper ",$(cat /home/bresilla/.cache/wal/wallpaper)"

# stupid hyprland things
c1="rgb(${color240:1})"
c15="rgb(${color242:1})"
c238="rgb(${color238:1})"

# sed -i "s/\($color1=rgb(\)130c06/\1FF0000/" file.txt
# sed -i "s/\($color1=rgb(\)[0-9a-fA-F]\{6\}/\$c1/" /env/dot/.config/hypr/hyprland.conf
# sed -i "s/\($color15=rgb(\)[0-9a-fA-F]\{6\}/\$c15/" /env/dot/.config/hypr/hyprland.conf
# sed -i "s/\($color238=rgb(\)[0-9a-fA-F]\{6\}/\$c238/" /env/dot/.config/hypr/hyprland.conf

# hyprctl keyword general:col.active_border $c1 $c15 45deg &
# hyprctl keyword general:col.inactive_border = $c238 &
# hyprctl hyprpaper reload ,"$(cat $TEMP/lule_wallpaper)"

# bspc config focused_border_color $color1 &
# bspc config normal_border_color $color239 &
# bspc config active_border_color $color239 &
# feh --no-fehbg --bg-scale $(cat $TEMP/lule_wallpaper) &

zedtheme &

# swaykill(){
#     killall swaybg
#     swaybg -i $(cat $TEMP/lule_wallpaper) &
# }
# swaykill &
