#!/bin/bash
source ~/.cache/wal/colors.sh
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar)

rofi "${ROFI_OPTIONS[@]}" -dmenu -sep ${2:-'\n'} -eh ${1:-1} -i -p ">>>"

#multiline
#echo -en "a\nb\x0fc\nd" | rofit 2 '\x0f'
