#!/usr/bin/env bash

current_window=$(hyprctl activewindow | head -1 | choose 1)
is_floating=$(hyprctl activewindow | grep floating | cut -d":" -f2 | xargs)

# @option --name   Window name
# @option --width  Window width in percent
# @option --height Window height in percent
# @option --monitor  Monitor to move window to
# @option --terminal  Terminal to use
eval "$(argc --argc-eval "$0" "$@")"

if [ $is_floating == "0" ]; then
    echo $current_window > /tmp/hyprscratch_current_window
fi

hyprscratch $argc_name "[float;size $argc_width% $argc_height%;center] $argc_terminal --title $argc_name" eager
hyprctl dispatch movewindow mon:$argc_monitor

if [ $current_title == $argc_name ]; then
    new_window=$(cat /tmp/hyprscratch_current_window)
    hyprctl dispatch focuswindow address:0x$new_window
fi


