#!/bin/bash
FILEPATH=$(readlink -f "$1")
bash $HOME/.config/zathura/genzathrc > $HOME/.config/zathura/zathurarc
#bash $HOME/Dots/.config/zathura/genzathrc > $HOME/Dots/.config/zathura/zathurarc
/usr/bin/zathura --config-dir="$HOME/.config/zathura/" "$FILEPATH" &
