return function(ctx)
    hl.on("hyprland.start", function()
        hl.exec_cmd("eval $(gnome-keyring-daemon --start)")
        hl.exec_cmd("export SSH_AUTH_SOCK")

        hl.exec_cmd("/env/bin/lule daemon --loop=360 -- start")
        hl.exec_cmd("/env/bin/clipse -listen")
        hl.exec_cmd("/env/bin/evsieve --input /dev/input/event2 grab --map key:capslock key:f12 --output")
        hl.exec_cmd([[lemonade server --port=12244 --allow="100.68.0.0/16"]])
        ctx.reload_plugins_and_apply_settings()
        hl.exec_cmd("/home/bresilla/.config/quickshell/launch.sh")
        hl.exec_cmd("hyprpaper")
        hl.exec_cmd([[hyprctl setcursor "BreezeX-Black" 60]])
        hl.exec_cmd("systemctl --user start hyprpolkitagent")
    end)
end
