#!/usr/bin/env bash

# @cmd connect to remote server via rdp
# @alias r
# @arg host!
# @flag -x --xfreerdp3
# @option -u --user
# @option -p --password
# @option -s --size mon%
rdp() {
    [[ -z $argc_user ]] && argc_user=bresilla
    [[ -z $argc_password ]] && argc_password=Batman:7

    if [[ -z $argc_xfreerdp3 ]]; then
        runner="flatpak run com.freerdp.FreeRDP"
    else
        runner="/usr/bin/xfreerdp3"
        [[ ! -x $runner ]] && runner="/usr/bin/xfreerdp"
    fi

    if [[ -z $argc_size ]]; then
        size_line="/dynamic-resolution"
        size_line_b=""
    else
        WIDTH_PRE=$(hyprctl monitors -j | jq -r '.[] | select(.focused==true) | .width')
        HEIGHT_PRE=$(hyprctl monitors -j | jq -r '.[] | select(.focused==true) | .height')
        SCALE_RAW="${argc_size%%%}"
        WIDTH=$(awk -v w="$WIDTH_PRE" -v p="$SCALE_RAW" 'BEGIN{printf "%d", w*p/100}')
        HEIGHT=$(awk -v h="$HEIGHT_PRE" -v p="$SCALE_RAW" 'BEGIN{printf "%d", h*p/100}')
        size_line="/size:${WIDTH}x${HEIGHT}"
        size_line_b="/smart-sizing"
    fi

    printf "%s\n" \
        "/v:${argc_host}" \
        "/u:${argc_user}" \
        "/p:${argc_password}" \
        "$size_line" \
        "$size_line_b" \
        "+compression" \
        "+clipboard" \
        "+home-drive" \
        "/sound:sys:alsa" \
        "/mouse:relative:on" \
        "+mouse-relative" \
        "-grab-keyboard" \
        "/gfx:AVC444" \
        "/rfx" \
        "/network:lan" \
        "/cert:tofu" \
        "/sec:tls" \
        | $runner /args-from:stdin
}

# @cmd connect to remote server via vnc
# @alias v
# @arg host!
# @option -d --display
# @option -p --password
vnc() {
    [[ -z $argc_password ]] && argc_password=Batman:7
    [[ -z $argc_display ]] && argc_display=1
    VNC_PASSWORD=$argc_password vncviewer $argc_host:$argc_display
}

# @cmd connect to remote server via sunshine
# @alias s
# @arg host!
sun() {
    moonlight stream -1080 -fps 30 -bitrate 3000 -app Desktop $argc_host
}

eval "$(argc --argc-eval "$0" "$@")"

