#!/bin/bash
distro_name=$(systemd-detect-virt | xargs)
if [[ $distro_name == "lxc" ]]; then
    printf "lxc"
elif [[ $distro_name == "qemu" ]]; then
    printf "qemu"
elif [[ $distro_name == "kvm" ]]; then
    printf "kvm"
else
    printf "VM"
fi
