label = "ros"
name = "ros"

[[file]]
  destination = ".clang-format"
  template = "ros/.clang-format"

[[file]]
  destination = ".clang-tidy"
  template = "ros/.clang-tidy"

[[file]]
  destination = ".envrc"
  template = "ros/.envrc"

[[file]]
  destination = ".gitignore"
  template = "ros/.gitignore"

[[file]]
  destination = ".gitmodules"
  template = "ros/.gitmodules"

[[file]]
  destination = "flake.nix"
  template = "ros/flake.nix"

[[file]]
  destination = "AUTHORS.md"
  template = "AUTHORS.md"

[[file]]
  destination = "CHANGELOG.md"
  template = "CHANGELOG.md"

[[file]]
  destination = "CMakeLists.txt"
  template = "ros/CMakeLists.txt"

[[file]]
  destination = "CONDUCT.md"
  template = "CONDUCT.md"

[[file]]
  destination = "CONTRIBUTING.md"
  template = "CONTRIBUTING.md"

[[file]]
  destination = "LICENSE.md"
  template = "LICENSE.md"

[[file]]
  destination = "README.md"
  template = "README.md"

[[folder]]
  destination = ".github/"
  template = "ros/.github"

[[folder]]
  destination = "cmake/"
  template = "ros/cmake"

[[folder]]
  destination = "include/"
  template = "ros/include"

[[folder]]
  destination = "src/"
  template = "ros/src"

[[folder]]
  destination = "tests/"
  template = "ros/tests"

[[script]]
  name = "readme.sh"
  type = "post"
  execNumber = 2
  runAsSudo = false
  args = []

[[script]]
  name = "direnv.sh"
  type = "post"
  execNumber = 3
  runAsSudo = false
  args = []

[[script]]
  name = "git.sh"
  type = "post"
  execNumber = 4
  runAsSudo = false
  args = []

[[script]]
  name = "ros.sh"
  type = "post"
  execNumber = 5
  runAsSudo = false
  args = []
