[global]
device_name = "core"
device_type = "computer"
backend = "pulseaudio"
volume_controller = "softvol"
bitrate = 320
cache_path = "/home/bresilla/.cache/spotifyd"
use_mpris = true
dbus_type = "session"
