#!/bin/zsh

# check if we passed a directory as the first arg
local cwd="$PWD"
local p="$1"
[ "$1" != "" ] && shift
if [ -d "$p" ]; then
	p="$(realpath $p)"
	cwd="$p"
elif [ -f "$p" ]; then
	p="$(realpath $p)"
	cwd="$(dirname $p)"
fi

# common pathes that needs to be r/w
JAIL_RW=("$HOME/.local/state/nvim" "$HOME/.local/share/nvim" "$HOME/.cache/nvim" "$HOME/.gnupg" "$p")
# go mod cache if available
which go &>/dev/null && JAIL_RW+=("$(go env GOMODCACHE)")
# lazygit if available
[ -d "$HOME/.config/lazygit" ] && JAIL_RW+=("$HOME/.config/lazygit")

JAIL="firejail --noprofile --caps.drop=all --nonewprivs --seccomp --noroot --disable-mnt --read-only=\"$HOME\""
for jp in $JAIL_RW; do
	JAIL="$JAIL --read-write=\"$jp\""
done

pushd $cwd
eval $JAIL nvim $p $@
popd

