return {
  api = 1, id = "material", name = "Material",
  tokens = require("themes.material.tokens"),
  motion = "themes.material.motion",
  components = "themes.material.components",
  lock = "themes.material.lock", greet = "themes.material.greet",
  views = {
    keyboard = "themes.layouts.views.keyboard",
    bar = "themes.layouts.views.bar",
    side_panel = "themes.layouts.views.side_panel",
    connectivity = "themes.layouts.views.connectivity",
    utilities = "themes.layouts.views.utilities",
    bottom = "themes.layouts.views.bottom",
    dashboard = "themes.layouts.views.dashboard",
    notification_history = "themes.layouts.views.notification_history",
    rail = "themes.material.views.rail",
    frame = "themes.material.views.frame",
    levels = "themes.layouts.views.levels",
    notifications = "themes.layouts.views.notifications",
    polkit = "themes.layouts.views.polkit",
    authsteps = "themes.layouts.views.authsteps",
    headphones = "themes.layouts.views.headphones",
    session = "themes.layouts.views.session",
    launcher = "themes.layouts.views.launcher",
    assistant = "themes.layouts.views.assistant",
    drop = "themes.layouts.views.drop",
    lule_page = "themes.layouts.views.lule_page",
    tasks_page = "themes.layouts.views.tasks_page",
    calendar_page = "themes.layouts.views.calendar_page",
    planner_widgets = "themes.layouts.views.planner_widgets",
    capture_view = "themes.layouts.views.capture_view",
    capture_editor = "themes.layouts.views.capture_editor",
    graphs = "themes.layouts.views.graphs",
    dashboard_media = "themes.layouts.views.dashboard_media",
    dashboard_performance = "themes.layouts.views.dashboard_performance",
    dashboard_battery = "themes.layouts.views.dashboard_battery",
    dashboard_weather = "themes.layouts.views.dashboard_weather",
    sound_page = "themes.layouts.views.sound_page",
    equalizer_page = "themes.layouts.views.equalizer_page",
    net_pages = "themes.layouts.views.net_pages",
    power_page = "themes.layouts.views.power_page",
    bar_page = "themes.layouts.views.bar_page",
  },
}
