#!/bin/bash

# @cmd connect to remote server via rdp
# @alias r
# @arg host!
# @option -u --user
# @option -p --password
rdp() {
    [[ -z $argc_password ]] && argc_password=Batman:7
    [[ -z $argc_user ]] && argc_user=bresilla

    /usr/bin/xfreerdp3 +grab-keyboard -compression +clipboard +home-drive /u:$argc_user /p:"$argc_password" /dynamic-resolution /sound:sys:alsa /mouse:relative:on +mouse-relative /rfx /gfx /v:$argc_host
}

# @cmd connect to remote server via vnc
# @alias v
# @arg host!
# @option -d --display
# @option -p --password
vnc() {
    [[ -z $argc_password ]] && argc_password=Batman:7
    [[ -z $argc_display ]] && argc_display=1
    VNC_PASSWORD=$argc_password vncviewer $argc_host:$argc_display
}

# @cmd connect to remote server via sunshine
# @alias s
# @arg host!
sun() {
    moonlight stream -1080 -fps 30 -bitrate 3000 -app Desktop $argc_host
}

eval "$(argc --argc-eval "$0" "$@")"
