#!/usr/bin/env bash

# get tmux context
current_tty=$(tmux display-message -p "#{pane_tty}")
pane_id=$(tmux display-message -p "#{pane_id}")
current_path=$(tmux display-message -p "#{pane_current_path}")
curr_edit=$(cat /tmp/current_editing_file)

if ! ps -t "$current_tty" -o comm= | grep -qiE '^(n?vim|view|hx)$'; then
    exit 0
fi

editor=$(ps -t "$current_tty" -o comm= | awk 'NF' | tail -n1 | tr -d '[:space:]')


# @cmd pick file with explorer
# @alias e
explorer() {
    if [[ -n "$curr_edit" ]]; then
        current_path=$curr_edit
    fi
    pick=$(yazi --chooser-file=/dev/stdout "$current_path")
    # pick=$(nnn -p /dev/stdout "$current_path")
    [[ -z "$pick" ]] && exit 0
    if [[ "$pick" == "$current_path" ]]; then
        exit 0
    fi
    case "$editor" in
      nvim|vim|view)
        tmux send-keys -t "$pane_id" ":e $pick" C-m
        ;;
      hx)
        tmux send-keys -t "$pane_id" ":open $pick" C-m
        ;;
    esac
}

# @cmd pick file with finder
# @alias f
finder() {
    pick=$(tv find)
    [[ -z "$pick" ]] && exit 0
    if [[ "$pick" == "$current_path" ]]; then
        exit 0
    fi
    case "$editor" in
      nvim|vim|view)
        tmux send-keys -t "$pane_id" ":e $pick" C-m
        ;;
      hx)
        tmux send-keys -t "$pane_id" ":open $pick" C-m
        ;;
    esac
}


# @cmd grep file for text
# @alias g
grepi() {
    pick=$(tv text)
    [[ -z "$pick" ]] && exit 0
    if [[ "$pick" == "$current_path" ]]; then
        exit 0
    fi
    case "$editor" in
      nvim|vim|view)
        tmux send-keys -t "$pane_id" ":e $pick" C-m
        ;;
      hx)
        tmux send-keys -t "$pane_id" ":open $pick" C-m
        ;;
    esac
}

eval "$(argc --argc-eval "$0" "$@")"
