#!/bin/bash
distro_name=$(systemd-detect-virt | xargs)
if [[ $distro_name == "lxc" ]]; then
    printf " >> "
elif [[ $distro_name == "qemu" ]]; then
    printf " :: "
elif [[ $distro_name == "kvm" ]]; then
    printf " :: "
else
    printf " :: "
fi
