name: tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: "2.2.4"
      - name: Cache Nim
        uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
            ~/.cache/nim
          key: ${{ runner.os }}-nim-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nim-
      - name: Install dependencies
        run: nimble install -y --depsOnly
      - name: Verify
        run: |
          nim check src/{{snake_name}}.nim
          nimble test -y
      - name: Build
        run: nim c -d:release --out:{{kebab_name}} src/{{snake_name}}.nim

