#!/usr/bin/env python3

import os, sys, random, time

def slt(img):
    return img.split("\n")

def get_scr_size():
    return [int(x) for x in os.popen("stty size", "r").read().split()]

def get_img_size(img):
    return [IMG.count("\n"), max([len(x) for x in slt(IMG)])]

def init():
    global scr, img
    os.system("tput civis -- invisible")
    os.system("clear")
    scr = get_scr_size()
    img = get_img_size(IMG)

colors = [
    [37, 31, 33, 34, 35, 36, 32],
    [31, 33, 34, 35, 36, 37, 30]
]

if len(sys.argv) == 2:
    forever = sys.argv[1]
    if forever == "forever":
        timeer = 0.05
else:
    forever = ""
    timeer = 0.02

def get_color(x, y, t):
    global colors, img
    f = x -max(img) +abs(t)
    off = random.randint(1, 15)
    for i in range(6, -1, -1):
        if f > y +(i *3) +off:
            if t >= 0:
                return "\033[" +str(colors[1][i]) +"m"
            elif t < 0:
                return "\033[" +str(colors[0][i]) +"m"
    return t <= 0 and "\033[30m" or "\033[" +str(colors[0][-1]) +"m"


IMG = open('/env/dot/bresilla/ascii', 'r').read()

init()
step = 6
frames = img[0] * step

try:
    while 1:
        for t in (list(range(-frames, step, step)) +list(range(frames, 0, -step))):
            print("\033[" +str(int((scr[0] -img[0]) /2)) +"H")
            for y in range(img[0]):
                print((" " *int((scr[1] -img[1])/ 2)) +"".join([(get_color(x, y, t) +slt(IMG)[y][x] +"\033[0m") for x in range(len(slt(IMG)[y]))]))
            if t == 0:
                time.sleep(timeer)
                colors[0].append(colors[0].pop(random.randint(1, 3)))
                init()
                if forever != "forever":
                    break
            time.sleep(timeer)
        os.system("tput cvvis")
        if forever != "forever":
            break
except KeyboardInterrupt:
    pass

os.system("clear")
print("\x1b[?25h")
