#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

dbus-run-session -- gnome-shell

#startxfce4 &                                                                                                                                                                                                                                 
#vncconfig -iconic &
