label = "conda"
name = "conda"

[[file]]
  destination = ".envrc"
  template = "conda/.envrc"

[[file]]
  destination = ".gitignore"
  template = "conda/.gitignore"

[[file]]
  destination = ".shell.nix"
  template = "conda/.shell.nix"

[[file]]
  destination = "AUTHORS.md"
  template = "AUTHORS.md"

[[file]]
  destination = "CHANGELOG.md"
  template = "CHANGELOG.md"

[[file]]
  destination = "CONDUCT.md"
  template = "CONDUCT.md"

[[file]]
  destination = "CONTRIBUTING.md"
  template = "CONTRIBUTING.md"

[[file]]
  destination = "LICENSE.md"
  template = "LICENSE.md"

[[file]]
  destination = "README.md"
  template = "README.md"

[[folder]]
  destination = "src/"
  template = ""

[[script]]
  name = "readme.sh"
  type = "post"
  execNumber = 2
  runAsSudo = false
  args = []

[[script]]
  name = "direnv.sh"
  type = "post"
  execNumber = 3
  runAsSudo = false
  args = []

[[script]]
  name = "git.sh"
  type = "post"
  execNumber = 4
  runAsSudo = false
  args = []

[[script]]
  name = "conda.sh"
  type = "post"
  execNumber = 5
  runAsSudo = false
  args = []
