btop {
    title = "btop"
    command = "kitty --title btop -e btop"
    rules = "float;size 80% 80%;center"
    options = "cover persist sticky shiny lazy show hide poly special tiled"
}

sdt {
    title = "sdt"
    command = "kitty --title sdt -e sdt"
    rules = "float;size 80% 80%;center"
    options = "cover persist sticky shiny lazy show hide poly special tiled"
}

note {
	title = "note"
	command = "kitty --title note -e zsh"
    rules = "float;size 90% 60%;center"
    options = "cover persist sticky shiny lazy show hide poly special tiled"
}

main {
	title = "main"
	command = "kitty --title main -e zsh"
	rules = "float;size 90% 60%;center"
	options = "cover persist sticky shiny lazy show hide poly special tiled"
}
