#!/bin/bash

if  [ "$1" == "fzf" ] || [ -z $1 ]; then
    runner=fzy
elif [ "$1" == "rofi" ]; then
    runner=rofit
fi

source $HOME/.cache/wal/colors.sh


foxy() {
    # PLACES_PATH="$HOME/.mozilla/firefox/dq7krxug.default-1630495882574/places.sqlite"
    PLACES_PATH="$HOME/.var/app/org.mozilla.firefox/.mozilla/firefox/gxw08cft.default-release/places.sqlite"
    DB_PATH=$(mktemp /tmp/ffhist.XXXXX)
    cp -f $PLACES_PATH $DB_PATH

    QUERY="
    SELECT
        url, title FROM moz_places
    WHERE
        url NOT LIKE '%google%search%'
    ORDER BY
        last_visit_date DESC,
        visit_count DESC;
    "

    SEP="∙"
    ENTRY=$(sqlite3 "$DB_PATH" "$QUERY" | sed -E 's/^https?:\/\///' | sed -E "s/\\/?\\|/ $SEP /" | sed -E "s/$SEP $//" | $runner)
    URL=$( echo "$ENTRY" | sed "s/$SEP.*//g" )

    [[ "$URL" = "" ]] && exit

    $BROWSER "https://$URL"
}

srch=search
mark=bookmarks
loca=proxmox
hist=history
list=playlist
pkgs=packages
apps=app-list

another=$(echo "\
$hist
$mark
$loca
$srch
$list
$apps
$pkgs\
" | $runner)


if [ "$another" == "$srch" ] ; then
    surfraw -browser=$BROWSER $(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' | $runner)

elif [ "$another" == "$hist" ] ; then
    foxy

elif [ "$another" == "$mark" ] ; then
    LINK=$(/env/bin/bookmark --file "$HOME/.local/share/bookmark/webmarks_v0.1.json" list -g default| tail -n+3 | sed 's/^\w*\s*//' | $runner | /env/bin/choose 1)
    if [[ -z $LINK ]]; then
        browsy
    else
        $BROWSER $LINK
    fi

elif [ "$another" == "$loca" ] ; then
    LINK=$(/env/bin/bookmark --file "$HOME/.local/share/bookmark/webmarks_v0.1.json" list -g proxmox | tail -n+3 | sed 's/^\w*\s*//' | $runner | /env/bin/choose 1)
    if [[ -z $LINK ]]; then
        browsy
    else
        $BROWSER $LINK
    fi

elif [ "$another" == "$list" ] ; then
    LINK=$(/env/bin/bookmark --file "$HOME/.local/share/bookmark/playmarks_v0.1.json" list | tail -n+3 | sed 's/^\w*\s*//' | $runner | /env/bin/choose 1)
    if [[ -z $LINK ]]; then
        browsy
    else
        /env/dot/.func/media/play $LINK
    fi

elif [ "$another" == "$apps" ] ; then
    LINK=$(/env/bin/bookmark --file "$HOME/.local/share/bookmark/climarks_v0.1.json" list | tail -n+3 | sed 's/^\w*\s*//' | $runner | /env/bin/choose 1)
    if [[ -z $LINK ]]; then
        browsy
    else
        $BROWSER $LINK
    fi

elif [ "$another" == "$pkgs" ] ; then
    LINK=$runner
    if [[ -z $LINK ]]; then
        browsy
    else
        $BROWSER "https://pkgs.org/search/?q=$LINK"
    fi

else
    # if another is empty then exit
    [ -z "$another" ] && exit 0
    # Check if the input is a link
    if [[ "$another" =~ ^https?:// ]] || [[ "$another" =~ \.[a-z]{2,} ]]; then
        $BROWSER "$another"
    else
        $BROWSER "https://duckduckgo.com/?q=$another"
    fi
fi
