#!/usr/bin/env bash

# Zellij version of edux - simple floating pane launcher

TOOL="$1"

current_path=$(pwd)
view=$(ps -o comm= -p $(ps -o ppid= -p $$) 2>/dev/null | tail -1)

case "$view" in
  nvim|vim|view|hx)
    context="editor"
    ;;
  *)
    context="shell"
    ;;
esac

case "$TOOL" in
  explorer)
    /env/dot/.func/run/inter-zj explorer "$current_path" "$context" "$view"
    ;;
  replace)
    /env/dot/.func/run/inter-zj replace "$current_path" "$context" "$view"
    ;;
  picker)
    /env/dot/.func/run/inter-zj picker "$current_path" "$context" "$view"
    ;;
  finder)
    /env/dot/.func/run/inter-zj finder "$current_path" "$context" "$view"
    ;;
  buffers)
    /env/dot/.func/run/inter-zj buffers "$current_path" "$context" "$view"
    ;;
  quickfix)
    /env/dot/.func/run/inter-zj quickfix "$current_path" "$context" "$view"
    ;;
  *)
    echo "Unknown tool: $TOOL"
    exit 1
    ;;
esac
