#!/bin/bash
comd=":e"

# @cmd pick file with explorer
# @arg current_path!
# @arg context!
# @arg pane_id!
# @arg view!
explorer() {
    local context=$argc_context
    local current_path=$argc_current_path
    local pane_id=$argc_pane_id
    local view=$argc_view
    if [[ "$context" == "shell" ]]; then
        local tmp_dir="$(mktemp -t "yazi-cwd.XXXXXX")"
        yazi "$current_path" --cwd-file="$tmp_dir" --chooser-file="$tmp_dir"
        if cwd="$(cat -- "$tmp_dir")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
            if [ -f "$cwd" ]; then
                parent_dir=$(dirname "$cwd")
                filetype=$(xdg-mime query filetype $cwd | cut -d"/" -f1)
                if [[ $filetype = "text" ]]; then
                    tmux send-keys -t "$pane_id" "cd $parent_dir && $EDITOR $cwd" C-m
                else
                    tmux send-keys -t "$pane_id" "cd $parent_dir && xdg-open $cwd" C-m
                fi
            elif [ -d "$cwd" ]; then
                tmux send-keys -t "$pane_id" "cd $cwd" C-m
            fi
        fi
        rm -f -- "$tmp_dir"
    else
        full_name=/tmp/"$view"_"$(basename "$current_path")"_current_file
        pick=$(yazi $(cat $full_name) --chooser-file=/dev/stdout)
        [[ ! -f "$pick" ]] && exit 0
        tmux send-keys -t "$pane_id" "$comd $pick" C-m
    fi
}

# @cmd pick file with finder
# @arg current_path!
# @arg context!
# @arg pane_id!
# @arg view!
picker() {
    local context=$argc_context
    local current_path=$argc_current_path
    local pane_id=$argc_pane_id
    local view=$argc_view
    pick=$(tv find)
    [[ -z "$pick" ]] && exit 0
    [[ "$pick" == "$current_path" ]] && exit 0
    if [[ "$context" != "editor" ]]; then
        exit 0
    fi
    tmux send-keys -t "$pane_id" "$comd $pick" C-m
}


# @cmd find text in file
# @arg current_path!
# @arg context!
# @arg pane_id!
# @arg view!
finder() {
    local context=$argc_context
    local current_path=$argc_current_path
    local pane_id=$argc_pane_id
    local view=$argc_view
    IFS=':' read -r pick nr < <(tv text)
    [[ -z "$pick" ]] && exit 0
    [[ "$pick" == "$current_path" ]] && exit 0
    if [[ "$context" != "editor" ]]; then
        exit 0
    fi
    tmux send-keys -t "$pane_id" "$comd $pick" C-m
}


# @cmd replace text in file
# @arg current_path!
# @arg context!
# @arg pane_id!
# @arg view!
replace() {
    local context=$argc_context
    local current_path=$argc_current_path
    local pane_id=$argc_pane_id
    local view=$argc_view
    serpl -p $current_path
}

# @cmd list buffers
# @arg current_path!
# @arg context!
# @arg pane_id!
# @arg view!
buffers() {
    local context=$argc_context
    local current_path=$argc_current_path
    local pane_id=$argc_pane_id
    local view=$argc_view
    [[ "$context" != "editor" ]] && exit 
    buffers_list=/tmp/"$view"_"$only_name"_open_buffers
    [[ ! -f "$buffers_list" ]] && exit 0
    pick=$(cat $buffers_list | tv --preview 'bat -n --color=always {0}')
    [[ -z "$pick" ]] && exit 0
    tmux send-keys -t "$pane_id" "$comd $pick" C-m
}


# @cmd list quickfix
# @arg current_path!
# @arg context!
# @arg pane_id!
# @arg view!
quickfix() {
    local context=$argc_context
    local current_path=$argc_current_path
    local pane_id=$argc_pane_id
    local view=$argc_view
    quickfix_list=$current_path/.quickfix
    [[ ! -f "$quickfix_list" ]] && exit 0
    pick=$(cat $quickfix_list | tv)
    file=$(echo $pick | cut -d: -f1)
    line=$(echo $pick | cut -d: -f2)
    col=$(echo $pick | cut -d: -f3)
    # if [[ "$context" != "editor" ]]; then
        # echo $context $argc_view
        # read
        # exit 0
    # fi
    [[ -z "$file" ]] && exit 0
    tmux send-keys -t "$pane_id" ":e $file" C-m
    tmux send-keys -t "$pane_id" ":cal cursor($line, $col)" C-m
}

eval "$(argc --argc-eval "$0" "$@")"
