#!/bin/bash

REMOTE_USER="bresilla"
REMOTE_HOST="echo.zerotier"
WALLPAPER_PATH=$(cat /tmp/lule_wallpaper)

ssh "$REMOTE_USER@$REMOTE_HOST" <<EOF
export DISPLAY=:1
export XDG_RUNTIME_DIR=/run/user/\$(id -u)
export DBUS_SESSION_BUS_ADDRESS="unix:path=\$XDG_RUNTIME_DIR/bus"
gsettings set org.gnome.desktop.background picture-uri "file://$WALLPAPER_PATH"
EOF
