#!/bin/bash

export isaac_sim_package_path=/opt/isaac # adjust to right folder

export ROS_DISTRO=jazzy # can be humble or jazzy
# export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
# Can only be set once per terminal.
# Setting this command multiple times will append the internal library path again potentially leading to conflicts
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$isaac_sim_package_path/exts/isaacsim.ros2.bridge/$ROS_DISTRO/lib


$isaac_sim_package_path/isaac-sim.sh
