#!/bin/sh

export INDIRENV=true;
export DIRENV_TOP=$PWD;
local BLUE='\033[0;34m';
local GREEN='\033[0;32m';
local RED='\033[0;31m';
local NC='\033[0m'

use_devbox() {
    watch_file devbox.json
    eval $(devbox shell --print-env)
}

use_devenv() {
    watch_file devenv.nix
    watch_file devenv.yaml
    watch_file devenv.lock
    eval "$(devenv print-dev-env)"
}

use_nvidia() {
    export __NV_PRIME_RENDER_OFFLOAD=1
    export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export __VK_LAYER_NV_optimus=NVIDIA_only
}

layout_pixi() {
    watch_file pixi.lock
    eval "$(pixi shell-hook)"
}

layout_mamba() {
    export HASHER=`echo $PWD | md5sum | cut -d" " -f1`
    export MAMBA_ROOT_PREFIX="/pkg/mamba";
    export VENV=$MAMBA_ROOT_PREFIX/envs/$HASHER
    eval "$(micromamba shell hook --shell=bash)"

    if [[ -d $VENV/conda-meta ]]; then
        micromamba activate $VENV
        micromamba info
    else
        micromamba create -n $HASHER mamba libmambapy python=${1:-3.10} -c conda-forge
        micromamba activate $VENV
        micromamba info
    fi
}

layout_mambaid(){
    export HASHER=${2:-c50e54e785a4b687578a7c854f5dccc9}
    export MAMBA_ROOT_PREFIX="/pkg/mamba";
    export VENV=$MAMBA_ROOT_PREFIX/envs/$HASHER
    eval "$(micromamba shell hook --shell=bash)"

    if [[ -d $VENV/conda-meta ]]; then
        micromamba activate $VENV
        micromamba info
    else
        micromamba create -n $HASHER mamba libmambapy python=${1:-3.10} -c conda-forge
        micromamba activate $VENV
        micromamba info
    fi
}

layout_localmamba() {
    export MAMBA_ROOT_PREFIX="$PWD/.direnv/mamba";
    export VENV=$MAMBA_ROOT_PREFIX/envs/`basename $PWD`
    eval "$(micromamba shell hook --shell=bash)"

    if [[ -d $VENV/conda-meta ]]; then
        micromamba activate $VENV
        micromamba info
    else
        micromamba create -n `basename $PWD` mamba libmambapy python=${1:-3.9} -c conda-forge
        micromamba activate $VENV
        micromamba info
    fi
}

layout_ros2() {
    source /etc/lsb-release
    export TOP_HEAD=$PWD
    if [[ $DISTRIB_CODENAME == "jammy" ]]; then
        source "/opt/ros/humble/setup.sh"
        echo "UBUNTU 22.04"
    elif [[ $DISTRIB_CODENAME == "noble" ]]; then
        source "/opt/ros/jazzy/setup.sh"
        echo "UBUNTU 24.04"
    fi
    source $TOP_HEAD/install/setup.sh
    export_alias build 'cd $TOP_HEAD && colcon build'
    eval "$(register-python-argcomplete3 ros2)"
    eval "$(register-python-argcomplete3 colcon)"
}

export_function() {
  local name=$1
  local alias_dir=$PWD/.direnv/functions
  mkdir -p "$alias_dir"
  PATH_add "$alias_dir"
  local target="$alias_dir/$name"
  if declare -f "$name" >/dev/null; then
    echo "#!/bin/bash" > "$target"
    declare -f "$name" >> "$target" 2>/dev/null
    # Notice that we add shell variables to the function trigger.
    echo "$name \$*" >> "$target"
    chmod +x "$target"
  fi
}
# EXAMPLE
# woot() {
  # echo woot
# }
# export_function woot

export_alias() {
    local name=$1
    shift
    local alias_dir=$PWD/.direnv/aliases
    local target="$alias_dir/$name"
    mkdir -p "$alias_dir"
    PATH_add "$alias_dir"
    echo "#!/usr/bin/sh" > "$target"
    echo "$@" >> "$target"
    chmod +x "$target"
}
# EXAMPLE
# export_alias ll "ls -la"

tidyup(){
    [[ -d "$PWD/.direnv/functions" ]] && rm -r $PWD/.direnv/functions
    [[ -d "$PWD/.direnv/aliases" ]] && rm -r $PWD/.direnv/aliases
}
