#!/usr/bin/env bash

export LULE_S="$HOME/.config/profile/functions/wm/lule_colors"
export LULE_C="$HOME/.cache/lule"
# export LULE_W=/env/set/.animegen
export LULE_W=/env/set/.wallpaper

"$HOME/.local/bin/lule" create --theme=$(cat "$HOME/.cache/lule/theme") -- set

# hyprctl hyprpaper preload $(cat $HOME/.cache/wal/wallpaper)
# hyprctl hyprpaper wallpaper ",$(cat $HOME/.cache/wal/wallpaper)"

# hyprctl hyprpaper reload ,$(cat $HOME/.cache/wal/wallpaper)
