#!/bin/bash


[ "$(cat /home/bresilla/.cache/lule/theme)" = "light" ] && lule config --theme=dark > /tmp/lule_pipe || lule config --theme=light > /tmp/lule_pipe

# /env/bin/lule create --theme=$(cat /home/bresilla/.cache/lule/theme) -- set

# hyprctl hyprpaper preload $(cat /home/bresilla/.cache/wal/wallpaper)
# hyprctl hyprpaper wallpaper ",$(cat /home/bresilla/.cache/wal/wallpaper)"

# hyprctl hyprpaper reload ,$(cat /home/bresilla/.cache/wal/wallpaper)
