set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#FAF4FB guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#FAF4FB guibg=#110C12 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#C398BE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#A094A4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#796E7C guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#B2A6B5 guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#E0E3DD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#C398BE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#110C12 guibg=#FAF4FB guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#A094A4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=#B2A6B5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#796E7C guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#E0E3DD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#C791D4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#D39ADF guibg=NONE guisp=#D39ADF blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#A1A1A1 guibg=NONE guisp=#A1A1A1 blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#CDC7C1 guibg=NONE guisp=#CDC7C1 blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#AD9C90 guibg=NONE guisp=#AD9C90 blend=NONE gui=underline
highlight DiagnosticWarn guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#D7BEA7 guibg=#B2A6B5 guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#8E8192 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#D39ADF guibg=#B2A6B5 guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#D39ADF guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#CDC7C1 guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#D7BEA7 guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#CDC7C1 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#FAF4FB guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#D39ADF guibg=#FAF4FB guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#D39ADF guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#C398BE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#CDC7C1 guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#796E7C guibg=#B2A6B5 guisp=NONE blend=NONE gui=italic
highlight Function guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#B2A6B5 guibg=#C398BE guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#FAF4FB guibg=#110C12 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#E0E3DD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#8E8192 guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#FAF4FB guibg=#8E8192 guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#B2A6B5 guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#CDC7C1 guibg=NONE guisp=#8E8192 blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#796E7C guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#FAF4FB guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#C791D4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#C791D4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#796E7C guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#796E7C guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#AD9C90 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#A094A4 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#110C12 guibg=#A1A1A1 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#110C12 guibg=#CDC7C1 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#110C12 guibg=#D7BEA7 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#110C12 guibg=#E0E3DD guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#110C12 guibg=#D39ADF guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#110C12 guibg=#C398BE guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#B2A6B5 guibg=#C398BE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#8E8192 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#D7BEA7 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#796E7C guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#A094A4 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#796E7C guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#8E8192 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#D39ADF guibg=#FAF4FB guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#8E8192 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#C398BE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#FAF4FB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#796E7C guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#FAF4FB guibg=#CDC7C1 guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#A094A4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#FAF4FB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#8E8192 guibg=#AD9C90 guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#A094A4 guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#C791D4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#8E8192 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#D39ADF guibg=NONE guisp=#D39ADF blend=NONE gui=underline
highlight SpellCap guifg=#AD9C90 guibg=NONE guisp=#AD9C90 blend=NONE gui=underline
highlight SpellLocal guifg=#A1A1A1 guibg=NONE guisp=#A1A1A1 blend=NONE gui=underline
highlight SpellRare guifg=#E0E3DD guibg=NONE guisp=#E0E3DD blend=NONE gui=underline
highlight Statement guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#796E7C guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#A094A4 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#B88961 guibg=#D7BEA7 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#7B695B guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#E0E3DD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#8E8192 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#8E8192 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#D7BEA7 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#AD9C90 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#796E7C guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#110C12 guibg=#A094A4 guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#FAF4FB guibg=#CDC7C1 guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#796E7C guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#A094A4 guibg=#110C12 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#C791D4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#796E7C guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#FAF4FB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#E0E3DD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#E0E3DD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#E0E3DD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#FAF4FB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#FAF4FB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#FAF4FB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#6E6E6E guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#C791D4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#D7BEA7 guibg=#B2A6B5 guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#D39ADF guibg=#B2A6B5 guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#E0E3DD guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#D7BEA7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#A1A1A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#AD9C90 guibg=#B2A6B5 guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#B2A6B5 guisp=NONE blend=NONE gui=underline
highlight @type guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#CDC7C1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#AD9C90 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#D39ADF guibg=NONE guisp=NONE blend=NONE gui=NONE
