#! /bin/sh
###PROFILE
source /home/bresilla/.profile

###############################################################################################################################
#|||	SETTINGS
###############################################################################################################################
bspc config border_width         2
bspc config normal_border_color "#000000"
bspc config focused_border_color "#FFFFFF"
bspc config active_border_color "#000000"
bspc config presel_feedback_color "#575757"
bspc config window_gap          10
bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true
bspc config auto_alternate true
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

###############################################################################################################################
#|||	ASSIGNMENTS
###############################################################################################################################
bspc rule -a kitty state=floating sticky
bspc rule -a cool-retro-term state=floating sticky
bspc rule -a kittyled state=tiled
bspc rule -a feh state=floating
bspc rule -a sxiv state=floating
bspc rule -a mpv state=floating
bspc rule -a arandr state=floating
bspc rule -a dialect state=floating
bspc rule -a scrcpy state=floating
bspc rule -a MPlayer state=floating
bspc rule -a matplotlib state=floating
bspc rule -a python3 state=floating
bspc rule -a Matplotlib state=floating
bspc rule -a opencv state=floating
bspc rule -a URxvt state=floating
bspc rule -a FLTK state=floating
bspc rule -a "re.sonny.Junction" state=floating
bspc rule -a "monitorets" state=floating
bspc rule -a Oblogout state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a URxvt:launcher state=floating center sticky
bspc rule -a LAUNCHER state=floating center sticky rectangle=1200x300
bspc rule -a SSH state=floating center sticky rectangle=1200x300
bspc rule -a Boomer state=fullscreen sticky
bspc rule -a Screenkey manage=off
bspc rule -a GLava manage=off

bspc rule -a python3.9 state=floating sticky

###############################################################################################################################
#|||	SCRIPTS
###############################################################################################################################
$HOME/.config/bspwm/startup &
