-- require lush
local lush = require('lush')
local hsl = lush.hsl

local theme = lush(function(injected_functions)
    theme_light = {
        bg = "#ffffff",
        fg = "#000000",
        bg_alt = "#f0f0f0",
        fg_alt = "#505050",
        bg_dim = "#f8f8f8",
        fg_dim = "#282828",
        bg_active = "#e0e0e0",
        fg_active = "#191919",
        bg_inactive = "#efedef",
        fg_inactive = "#424242",
        bg_special_cold = "#dde3f4",
        fg_special_cold = "#093060",
        bg_special_mild = "#c4ede0",
        fg_special_mild = "#184034",
        bg_special_warm = "#f0e0d4",
        fg_special_warm = "#5d3026",
        bg_special_calm = "#f8ddea",
        fg_special_calm = "#61284f",
        red = "#a60000",
        green = "#005e00",
        yellow = "#813e00",
        blue = "#0030a6",
        magenta = "#721045",
        cyan = "#00538b",
        red_alt = "#972500",
        green_alt = "#315b00",
        yellow_alt = "#70480f",
        blue_alt = "#223fbf",
        magenta_alt = "#8f0075",
        cyan_alt = "#30517f",
        red_alt_other = "#a0132f",
        green_alt_other = "#145c33",
        yellow_alt_other = "#863927",
        blue_alt_other = "#0000bb",
        magenta_alt_other = "#5317ac",
        cyan_alt_other = "#005a5f",
        red_faint = "#7f1010",
        green_faint = "#104410",
        yellow_faint = "#5f4400",
        blue_faint = "#002f88",
        magenta_faint = "#752f50",
        cyan_faint = "#12506f",
        red_alt_faint = "#702f00",
        green_alt_faint = "#30440f",
        yellow_alt_faint = "#5d5000",
        blue_alt_faint = "#003f78",
        magenta_alt_faint = "#702565",
        cyan_alt_faint = "#354f6f",
        red_alt_other_faint = "#7f002f",
        green_alt_other_faint = "#0f443f",
        yellow_alt_other_faint = "#5e3a20",
        blue_alt_other_faint = "#1f2f6f",
        magenta_alt_other_faint = "#5f3f7f",
        cyan_alt_other_faint = "#2e584f",
        red_nuanced = "#5f0000",
        green_nuanced = "#004000",
        yellow_nuanced = "#3f3000",
        blue_nuanced = "#201f55",
        magenta_nuanced = "#541f4f",
        cyan_nuanced = "#0f3360",
        red_nuanced_bg = "#fff1f0",
        green_nuanced_bg = "#ecf7ed",
        yellow_nuanced_bg = "#fff3da",
        blue_nuanced_bg = "#f3f3ff",
        magenta_nuanced_bg = "#fdf0ff",
        cyan_nuanced_bg = "#ebf6fa",
        red_intense = "#b60000",
        green_intense = "#006800",
        yellow_intense = "#904200",
        blue_intense = "#1111ee",
        magenta_intense = "#7000e0",
        cyan_intense = "#205b93",
        red_subtle_bg = "#f2b0a2",
        green_subtle_bg = "#aecf90",
        yellow_subtle_bg = "#e4c340",
        blue_subtle_bg = "#b5d0ff",
        magenta_subtle_bg = "#f0d3ff",
        cyan_subtle_bg = "#c0efff",
        red_intense_bg = "#ff8892",
        green_intense_bg = "#5ada88",
        yellow_intense_bg = "#f5df23",
        blue_intense_bg = "#6aaeff",
        magenta_intense_bg = "#d5baff",
        cyan_intense_bg = "#42cbd4",
        red_refine_bg = "#ffcccc",
        red_refine_fg = "#780000",
        green_refine_bg = "#aceaac",
        green_refine_fg = "#004c00",
        yellow_refine_bg = "#fff29a",
        yellow_refine_fg = "#604000",
        blue_refine_bg = "#8ac7ff",
        blue_refine_fg = "#002288",
        magenta_refine_bg = "#ffccff",
        magenta_refine_fg = "#770077",
        cyan_refine_bg = "#8eecf4",
        cyan_refine_fg = "#004850",
        red_active = "#930000",
        green_active = "#005300",
        yellow_active = "#703700",
        blue_active = "#0033c0",
        magenta_active = "#6320a0",
        cyan_active = "#004882",
        red_fringe_bg = "#ff9a9a",
        green_fringe_bg = "#86cf86",
        yellow_fringe_bg = "#e0c050",
        blue_fringe_bg = "#82afff",
        magenta_fringe_bg = "#f0a3ff",
        cyan_fringe_bg = "#00d6e0",
    }
    theme_dark = {
        bg = "#000000",
        fg = "#ffffff",
        bg_alt = "#181a20",
        fg_alt = "#a8a8a8",
        bg_dim = "#110b11",
        fg_dim = "#e0e6f0",
        bg_active = "#2f2f2f",
        fg_active = "#f5f5f5",
        bg_inactive = "#202020",
        fg_inactive = "#bebebe",
        bg_special_cold = "#203448",
        fg_special_cold = "#c6eaff",
        bg_special_mild = "#00322e",
        fg_special_mild = "#bfebe0",
        bg_special_warm = "#382f27",
        fg_special_warm = "#f8dec0",
        bg_special_calm = "#392a48",
        fg_special_calm = "#fbd6f4",
        red = "#ff8059",
        green = "#44bc44",
        yellow = "#eecc00",
        blue = "#29aeff",
        magenta = "#feacd0",
        cyan = "#00d3d0",
        red_alt = "#f4923b",
        green_alt = "#80d200",
        yellow_alt = "#cfdf30",
        blue_alt = "#72a4ff",
        magenta_alt = "#f78fe7",
        cyan_alt = "#4ae8fc",
        red_alt_other = "#ff9977",
        green_alt_other = "#00cd68",
        yellow_alt_other = "#f0ce43",
        blue_alt_other = "#00bdfa",
        magenta_alt_other = "#b6a0ff",
        cyan_alt_other = "#6ae4b9",
        red_faint = "#ffa0a0",
        green_faint = "#88cf88",
        yellow_faint = "#d2b580",
        blue_faint = "#92baff",
        magenta_faint = "#e0b2d6",
        cyan_faint = "#a0bfdf",
        red_alt_faint = "#f5aa80",
        green_alt_faint = "#a8cf88",
        yellow_alt_faint = "#cabf77",
        blue_alt_faint = "#a4b0ff",
        magenta_alt_faint = "#ef9fe4",
        cyan_alt_faint = "#90c4ed",
        red_alt_other_faint = "#ff9fbf",
        green_alt_other_faint = "#88cfaf",
        yellow_alt_other_faint = "#d0ba95",
        blue_alt_other_faint = "#8fc5ff",
        magenta_alt_other_faint = "#d0b4ff",
        cyan_alt_other_faint = "#a4d0bb",
        red_nuanced = "#ffcccc",
        green_nuanced = "#b8e2b8",
        yellow_nuanced = "#dfdfb0",
        blue_nuanced = "#bfd9ff",
        magenta_nuanced = "#e5cfef",
        cyan_nuanced = "#a8e5e5",
        red_nuanced_bg = "#2c0614",
        green_nuanced_bg = "#001904",
        yellow_nuanced_bg = "#221000",
        blue_nuanced_bg = "#0f0e39",
        magenta_nuanced_bg = "#230631",
        cyan_nuanced_bg = "#041529",
        red_intense = "#fb6859",
        green_intense = "#00fc50",
        yellow_intense = "#ffdd00",
        blue_intense = "#00a2ff",
        magenta_intense = "#ff8bd4",
        cyan_intense = "#30ffc0",
        red_subtle_bg = "#762422",
        green_subtle_bg = "#2f4a00",
        yellow_subtle_bg = "#604200",
        blue_subtle_bg = "#10387c",
        magenta_subtle_bg = "#49366e",
        cyan_subtle_bg = "#00415e",
        red_intense_bg = "#a4202a",
        green_intense_bg = "#006800",
        yellow_intense_bg = "#874900",
        blue_intense_bg = "#2a40b8",
        magenta_intense_bg = "#7042a2",
        cyan_intense_bg = "#005f88",
        red_refine_bg = "#77002a",
        red_refine_fg = "#ffb9ab",
        green_refine_bg = "#00422a",
        green_refine_fg = "#9ff0cf",
        yellow_refine_bg = "#693200",
        yellow_refine_fg = "#e2d980",
        blue_refine_bg = "#242679",
        blue_refine_fg = "#8ec6ff",
        magenta_refine_bg = "#71206a",
        magenta_refine_fg = "#ffcaf0",
        cyan_refine_bg = "#004065",
        cyan_refine_fg = "#8ae4f2",
        red_active = "#ffa49e",
        green_active = "#70e030",
        yellow_active = "#efdf00",
        blue_active = "#00ccff",
        magenta_active = "#d0acff",
        cyan_active = "#00ddc0",
        red_fringe_bg = "#8f0040",
        green_fringe_bg = "#006000",
        yellow_fringe_bg = "#6f4a00",
        blue_fringe_bg = "#3a30ab",
        magenta_fringe_bg = "#692089",
        cyan_fringe_bg = "#0068a0",
    }

    -- function file_exists(file)
    --     local f = io.open(file, "rb")
    --     if f then f:close() end
    --     return f ~= nil
    -- end

    -- function fileToList(file)
    --     lines = {}
    --     if file_exists(file) then
    --         for line in io.lines(file) do
    --             lines[#lines + 1] = line
    --         end
    --     end
    --     return lines
    -- end

    -- rainbow = fileToList('/home/bresilla/.cache/wal/colors')
    -- themecolor = fileToList('/home/bresilla/.cache/wal/theme') or "dark"

    -- if (themecolor == "dark") then 
        cp = theme_dark
    -- else 
        -- cp = theme_light()
    -- end

    vim.notify(vim.inspect(cp.bg), vim.log.levels.INFO)
    local sym = injected_functions.sym
    return {
        Normal { bg = hsl(cp.bg), fg = hsl(208, 80, 80) },
    }
end)

return theme
