#!/bin/bash

# otter-launcher

#!/bin/bash

if [ "$1" == "fzf" ] || [ -z "$1" ]; then
    runner=fzy
elif [ "$1" == "rofi" ]; then
    runner=rofit
fi

source /home/bresilla/.cache/wal/colors.sh

# applaunch=$(flatpak list --columns=application | sort -u | $runner)

applaunch=$({ flatpak list --app --columns=application; find /env/app -maxdepth 1 -type f -printf '%f\n'; } | sort -u | $runner)

echo "$applaunch"

if [ -z "$applaunch" ]; then
    echo "No application found"
    exit 1
fi

if [[ $applaunch == *.AppImage ]]; then
    systemd-run --user --quiet --collect \
  --property=Type=exec \
  --property=KillMode=process \
  --property=StandardOutput=null \
  --property=StandardError=null \
  /env/app/"$applaunch"
else
    systemd-run --user --quiet --collect \
  --property=Type=exec \
  --property=KillMode=process \
  --property=StandardOutput=null \
  --property=StandardError=null \
  flatpak run "$applaunch"
fi
