#!/bin/bash

# get tmux context
current_tty=$(tmux display-message -p "#{pane_tty}")
pane_id=$(tmux display-message -p "#{pane_id}")
current_path=$(tmux display-message -p "#{pane_current_path}")
[[ -f /tmp/current_editing_file ]] && curr_edit=$(cat /tmp/current_editing_file)

view=$(ps -t "$current_tty" -o comm= | awk 'NF' | head -n2 | tail -n1 | tr -d '[:space:]')
case "$view" in
  nvim|vim|view)
    comd=":e"
    ;;
  hx)
    comd=":o"
    ;;
  zsh|fish|bash|sh)
    comd="$EDITOR"
    ;;
esac

# @cmd pick file with explorer
# @alias e
explorer() {
    if [[ "$comd" == "$EDITOR" ]]; then
        local tmp_dir="$(mktemp -t "yazi-cwd.XXXXXX")"
        yazi "$current_path" --cwd-file="$tmp_dir" --chooser-file="$tmp_dir"
        if cwd="$(cat -- "$tmp_dir")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
            if [ -f "$cwd" ]; then
                parent_dir=$(dirname "$cwd")
                filetype=$(xdg-mime query filetype $cwd | cut -d"/" -f1)
                if [[ $filetype = "text" ]]; then
                    tmux send-keys -t "$pane_id" "cd $parent_dir && $EDITOR $cwd" C-m
                else
                    tmux send-keys -t "$pane_id" "cd $parent_dir && xdg-open $cwd" C-m
                fi
            elif [ -d "$cwd" ]; then
                tmux send-keys -t "$pane_id" "cd $cwd" C-m
            fi
        fi
        rm -f -- "$tmp_dir"
    else
        [[ -n "$curr_edit" ]] && current_path=$curr_edit
        pick=$(yazi $curr_edit --chooser-file=/dev/stdout)
        [[ ! -f "$pick" ]] && exit 0
        tmux send-keys -t "$pane_id" "$comd $pick" C-m
    fi
}

# @cmd pick file with finder
# @alias p
picker() {
    pick=$(tv find)
    [[ -z "$pick" ]] && exit 0
    [[ "$pick" == "$current_path" ]] && exit 0
    tmux send-keys -t "$pane_id" "$comd $pick" C-m
}


# @cmd find text in file
# @alias f
finder() {
    IFS=':' read -r pick nr < <(tv text)
    [[ -z "$pick" ]] && exit 0
    [[ "$pick" == "$current_path" ]] && exit 0
    tmux send-keys -t "$pane_id" "$comd $pick" C-m
}

eval "$(argc --argc-eval "$0" "$@")"
