#!/bin/bash

#chci if in tmux display-popup and if yes then exit


current_tty=$(tmux display-message -p "#{pane_tty}")
pane_id=$(tmux display-message -p "#{pane_id}")
current_path=$(tmux display-message -p "#{pane_current_path}")
view=$(ps -t "$current_tty" -o comm= | awk 'NF' | head -n2 | tail -n1 | tr -d '[:space:]')
case "$view" in
  nvim|vim|view)
    context="editor"
    ;;
  hx)
    context="editor"
    ;;
  zsh|fish|bash|sh)
    context="shell"
    ;;
esac

# @cmd pick file with exp
# @arg val!
inter() {
    name="popup_inter_${current_path}_${argc_val}_${pane_id}_${view}"
    local session=$(echo $name | tr '/.%' '_')
    local current=$(tmux display-message -p -F "#{session_name}" 2>/dev/null)
    if [[ "$current" == "$session" || "$current" == *"popup"* ]]; then
        tmux detach-client
    else
        if ! tmux has-session -t "$session" 2>/dev/null; then
            tmux new-session -d -s "$session" -c "$current_path" -E bash -c "/env/dot/.func/run/inter $argc_val $current_path $context $pane_id $view"
            tmux set-option -t "$session" status off
        fi
        tmux display-popup -d "#{pane_current_path}" -w 80% -h 70% -E "tmux attach-session -t $session"
    fi
}


# @cmd run runn
# @arg cmd!
# @option --name
runn() {
    local session=$(echo "popup_runn_$current_path$argc_cmd$argc_name" | tr '/.' '_')
    local current=$(tmux display-message -p -F "#{session_name}" 2>/dev/null)
    if [[ "$current" == "$session" || "$current" == *"popup"* ]]; then
        tmux detach-client
    else
        if ! tmux has-session -t "$session" 2>/dev/null; then
            tmux new-session -d -s "$session" -c "$current_path" -E direnv exec "$current_path" bash -c "$argc_cmd; read -p ''"
            tmux set-option -t "$session" status off
        fi
        tmux display-popup -d "#{pane_current_path}" -w 80% -h 70% -E "tmux attach-session -t $session"
    fi
}

# @cmd run term
# @arg vb!
term() {
    local session=$(echo "popup_term_$current_path_$argc_vb" | tr '/.' '_')
    local current=$(tmux display-message -p -F"#{session_name}" 2>/dev/null)
    if [[ "$current" == "$session" || "$current" == *"popup"* ]]; then
        tmux detach-client
    else
        if ! tmux has-session -t "$session" 2>/dev/null; then
            tmux new-session -d -s "$session" -c "$current_path" -E direnv exec "$current_path" zsh -i
            tmux set-option -t "$session" status off
        fi
        tmux display-popup -d "#{pane_current_path}" -w 80% -h 70% -E "tmux attach-session -t $session"
    fi
}

eval "$(argc --argc-eval "$0" "$@")"
