#!/bin/bash
source /home/bresilla/.cache/wal/colors.sh
edit_with="kitty --class=til"
runner=fzy

selected=$(proji ls | head -n-1 | tail -n+4 | fzy -l 20 | cut -d "|" -f4)
cd $selected
setsid .direnv/aliases/coderun
exit
