theme = "trim"
# theme = "github_dark"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
mouse = true
bufferline = "always"
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-u = ["later"]
"minus" = ["goto_last_accessed_file"]
"pagedown" = ["half_page_down"]
C-pagedown = ["goto_next_buffer"]
"pageup" = ["half_page_up"]
C-pageup = ["goto_previous_buffer"]
"*" = [ "move_prev_word_start", "move_next_word_end", "search_selection", "global_search" ]
"#" = [ "toggle_comments" ]
# create a new minor mode bound to `+`
[keys.normal."+"]
m = ":run-shell-command make"
c = ":run-shell-command build"
r = ":run-shell-command run"

[keys.select]
"#" = [ "toggle_comments" ]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "  NORMAL  "
mode.insert = "  INSERT  "
mode.select = "  SELECT  "
