"diff.plus" = "#59dcb7"
"diff.delta" = "#dc7759"
"diff.minus" = "#dc597f"

"ui.background" = { bg = "000" }
"ui.virtual" = { fg = "237", modifiers = ["italic"] }
"ui.text" = { fg = "015" }

"ui.linenr" = { fg = "239" }
"ui.linenr.selected" = { fg = "015" }
"ui.cursorline" = { bg = "236" }

"ui.statusline" = { fg = "015", bg = "239" }
"ui.statusline.inactive" = { fg = "248", bg = "239" }
"ui.statusline.active" = { fg = "001", bg = "000" }

"ui.menu" = { fg = "255", bg = "239" }
"ui.menu.selected" = { fg = "255", bg = "241" }
"ui.popup" = { bg = "239" }
"ui.window" = { bg = "239" }
"ui.help" = { bg = "239", fg = "255" }

"ui.text.focus" = { fg = "015", modifiers= ["bold"] }
"ui.virtual.whitespace" = "242"
"ui.virtual.ruler" = { bg = "236" }


"ui.selection" = { bg = "#313f4e" }
"ui.cursor.match" = { fg = "#313f4e", bg = "#dc7759" }
"ui.cursor" = { fg = "#ABB2BF", bg = "1" }


"warning" = "#dc7759"
"error" = "#dc597f"
"info" = "#59dcb7"
"hint" = "#59c0dc"

# make diagnostic underlined, to distinguish with selection text.
diagnostic = { modifiers = ["underlined"] }

#LSP
"attribute" = "#dc7759"
"keyword" = { fg = "246", modifiers = ["bold"] }
"keyword.directive" = "#dcb659"
"namespace" = "002"
"punctuation" = "#dc7759"
"punctuation.delimiter" = "#dc7759"
"operator" = { fg = "#dc7759", modifiers = ["bold"] }
"special" = "#7fdc59"
"variable.other.member" = "004"
"variable" = "035"
"variable.parameter" = "#c6b8ad"
"type" = "023"
"type.builtin" = { fg = "011", modifiers = ["italic"] }
"constructor" = "047"
"function" = "009"
"function.macro" = { fg = "#dc7759", modifiers = ["bold"] }
"function.builtin" = { fg = "#59dcd8", modifiers = ["bold"] }
"comment" = { fg = "239", modifiers = ["italic"] }
"variable.builtin" = "059"
"constant" = "#59dcb7"
"constant.builtin" = "#59dcb7"
"string" = "#59dcb7"
"constant.numeric" = "#59c0dc"
"constant.character.escape" = { fg = "#7fdc59", modifiers = ["bold"] }
"label" = "#59c0dc"
"module" = "#d32c5d"

"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"

